#!/bin/bash

cd "$(dirname "$0")" || return

declare -i insiders=0
declare installed_extensions
declare added_extensions
declare added_extensions_count
declare removed_extensions
declare removed_extensions_count

while (($#)); do
	case $1 in
	--insiders | -i)
		insiders=1
		readonly insiders
		shift
		;;
	--* | -*)
		echo "error: unknown option '$1'" >&2
		exit 1
		;;
	*)
		shift
		;;
	esac
done

if [[ $insiders == 1 ]]; then
	installed_extensions="$(code-insiders --list-extensions)"
else
	installed_extensions="$(code --list-extensions)"
fi

readonly installed_extensions

if echo "$installed_extensions" | cmp -s extensions -; then
	echo 'Already up to date'
else
	added_extensions="$(echo "$installed_extensions" | diff -u extensions - | tail -n +4 | grep '^\+' | sed 's/\+//')"
	readonly added_extensions

	removed_extensions="$(echo "$installed_extensions" | diff -u - extensions | tail -n +4 | grep '^\+' | sed 's/\+//')"
	readonly removed_extensions

	if [[ -n $added_extensions ]]; then
		added_extensions_count="$(echo "$added_extensions" | wc -l | tr -d '[:space:]')"
		readonly added_extensions_count

		echo "Added $added_extensions_count extension$([[ added_extensions_count -gt 1 ]] && printf 's'):"
		echo "$added_extensions"
	fi

	[[ -n $added_extensions && -n $removed_extensions ]] && printf '\n'

	if [[ -n $removed_extensions ]]; then
		removed_extensions_count="$(echo "$removed_extensions" | wc -l | tr -d '[:space:]')"
		readonly removed_extensions_count

		echo "Removed $removed_extensions_count extension$([[ removed_extensions_count -gt 1 ]] && printf 's'):"
		echo "$removed_extensions"
	fi

	if [[ -n $installed_extensions ]]; then
		echo "$installed_extensions" >extensions
	else
		: >extensions
	fi
fi
