#!/bin/bash

cd "$(dirname "$0")" || return

declare -i dry_run=0
declare -i insiders=0
declare extensions_to_install

while (($#)); do
	case $1 in
	--dry-run | -n)
		dry_run=1
		readonly dry_run
		shift
		;;
	--insiders | -i)
		insiders=1
		readonly insiders=1
		shift
		;;
	--* | -*)
		echo "error: unknown option '$1'" >&2
		exit 1
		;;
	*)
		shift
		;;
	esac
done

if [[ $insiders == 1 ]]; then
	extensions_to_install="$(code-insiders --list-extensions | diff -u - extensions | tail -n +4 | grep '^\+' | sed 's/\+//')"
else
	extensions_to_install="$(code --list-extensions | diff -u - extensions | tail -n +4 | grep '^\+' | sed 's/\+//')"
fi

readonly extensions_to_install

if [[ -z $extensions_to_install ]]; then
	echo 'Nothing to install'
fi

if [[ $dry_run == 1 ]]; then
	echo "$extensions_to_install" | xargs -I {} echo 'Would install {}'
else
	if [[ $insiders == 1 ]]; then
		echo "$extensions_to_install" | xargs -I {} code-insiders --install-extension {}
	else
		echo "$extensions_to_install" | xargs -I {} code --install-extension {}
	fi
fi
