#!/bin/bash

cd "$(dirname "$0")" || return

declare extensions_to_install

extensions_to_install="$(code --list-extensions | diff -u - extensions | tail -n +4 | grep '^\+' | sed 's/\+//')"
readonly extensions_to_install

if [[ -z $extensions_to_install ]]; then
  echo 'Nothing to install'
fi

if [[ $DRY_RUN == 1 ]]; then
  echo "$extensions_to_install" | xargs -I {} echo 'Would install {}'
else
  echo "$extensions_to_install" | xargs -I {} -P 0 code --install-extension {}
fi
