#!/bin/bash

cd "$(dirname "$0")" || return

EXTENSIONS_TO_INSTALL=$(code --list-extensions | diff -u - extensions | tail -n +4 | grep '^\+' | sed 's/\+//')

if [[ $DRY_RUN == 1 ]]; then
  echo "$EXTENSIONS_TO_INSTALL" | xargs -I {} echo "Would install {}"
else
  echo "$EXTENSIONS_TO_INSTALL" | xargs -I {} -P 0 code --install-extension {}
fi
