#!/bin/sh

cd "$(dirname "$0")" || return

SOURCE_DIR=settings
TARGET_DIR=~/Library/Application\ Support/Code/User

set -o xtrace

ln -fs \
  "$PWD/$SOURCE_DIR/keybindings.json" \
  "$PWD/$SOURCE_DIR/settings.json" \
  "$PWD/$SOURCE_DIR/snippets" \
  "$TARGET_DIR"
