#!/bin/bash

cd "$(dirname "$0")" || return

declare -r settings_dir='settings'
declare -a settings=(
	"keybindings.json"
	"settings.json"
	"snippets/"
)

for setting in "${settings[@]}"; do
	ln -Ffs "$PWD/$settings_dir/$setting" "$HOME/Library/Application Support/Code/User"
	ln -Ffs "$PWD/$settings_dir/$setting" "$HOME/Library/Application Support/Code - Insiders/User"
done
