#!/bin/bash

cd "$(dirname "$0")" || return

declare extensions_to_uninstall
extensions_to_uninstall="$(code --list-extensions | diff -u extensions - | tail -n +4 | grep '^\+' | sed 's/\+//')"
readonly extensions_to_uninstall

if [[ -z $extensions_to_uninstall ]]; then
  echo 'Nothing to uninstall'
fi

if [[ $DRY_RUN == 1 ]]; then
  echo "$extensions_to_uninstall" | xargs -I {} echo 'Would uninstall {}'
else
  echo "$extensions_to_uninstall" | xargs -I {} -P 0 code --uninstall-extension {}
fi
