#!/bin/bash

cd "$(dirname "$0")" || return

declare -i dry_run=0
declare extensions_to_uninstall

while (($#)); do
	case $1 in
	--dry-run | -n)
		dry_run=1
		readonly dry_run
		shift
		;;
	--* | -*)
		echo "error: unknown option '$1'" >&2
		exit 1
		;;
	*)
		shift
		;;
	esac
done

extensions_to_uninstall="$(code --list-extensions | diff -u extensions - | tail -n +4 | grep '^\+' | sed 's/\+//')"
readonly extensions_to_uninstall

if [[ -z $extensions_to_uninstall ]]; then
	echo 'Nothing to uninstall'
fi

if [[ $dry_run == 1 ]]; then
	echo "$extensions_to_uninstall" | xargs -I {} echo 'Would uninstall {}'
else
	echo "$extensions_to_uninstall" | xargs -I {} code --uninstall-extension {}
fi
